# Define URLs
urls=(
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Gemini/Gemini.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/OpenAI/OpenAI.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Bing/Bing.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Claude/Claude.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Facebook/Facebook.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/TikTok/TikTok.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Line/Line.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Telegram/Telegram.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Spotify/Spotify.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Netflix/Netflix.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/YouTube/YouTube.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/TruthSocial/TruthSocial.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Reddit/Reddit.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Instagram/Instagram.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/GlobalMedia/GlobalMedia.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Global/Global.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Advertising/Advertising.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/CCB/CCB.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/ABC/ABC.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/BOC/BOC.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/BOCOM/BOCOM.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/ICBC/ICBC.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/CMB/CMB.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Hijacking/Hijacking.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/ChinaMedia/ChinaMedia.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Apple/Apple.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/SystemOTA/SystemOTA.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/China/China.list"
    "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/ChinaIPs/ChinaIPs.list"
)

# Define output filenames
files=(
    "Gemini.list"
    "OpenAI.list"
    "Bing.list"
    "Claude.list"
    "Facebook.list"
    "TikTok.list"
    "Line.list"
    "Telegram.list"
    "Spotify.list"
    "Netflix.list"
    "YouTube.list"
    "TruthSocial.list"
    "Reddit.list"
    "Instagram.list"
    "GlobalMedia.list"
    "Global.list"
    "Advertising.list"
    "CCB.list"
    "ABC.list"
    "BOC.list"
    "BOCOM.list"
    "ICBC.list"
    "CMB.list"
    "Hijacking.list"
    "ChinaMedia.list"
    "Apple.list"
    "SystemOTA.list"
    "China.list"
    "ChinaIPs.list"
)

# Fetch and write data
for i in ${!urls[@]}; do
    curl -s ${urls[$i]} -o ${files[$i]}
done
